version: "3"

services:
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: certonly --force-renewal --webroot --webroot-path=/var/www/certbot --email $EMAIL --agree-tos --no-eff-email -d $SERVER_NAME
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - var-www-certbot:/var/www/certbot

volumes:
  etc-letsencrypt:
  var-www-certbot:
