# Generated by Django 4.1.6 on 2026-04-06 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecordingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('count_failed', models.PositiveIntegerField(default=0)),
                ('count_canceled', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='RecordingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=250, unique=True)),
                ('meeting_id', models.CharField(max_length=250)),
                ('datetime_created', models.DateTimeField()),
                ('datetime_stopped', models.DateTimeField()),
                ('url', models.URLField(default='')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='TypeRecordingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Тип конференции',
                'verbose_name_plural': 'Типы конференций',
            },
        ),
        migrations.CreateModel(
            name='RecordingTaskIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=36, unique=True, validators=[django.core.validators.MinLengthValidator(36), django.core.validators.MaxLengthValidator(36)])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не обработана'), (2, 'Ожидает'), (3, 'Обрабатывается'), (4, 'Завершена'), (5, 'Загружена'), (6, 'Неудачно')], default=1)),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RepackingApp.orderrecordingmodel')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RepackingApp.recordingmodel', to_field='record_id')),
            ],
            options={
                'verbose_name': 'Запись обработки',
                'verbose_name_plural': 'Записи обработки',
                'unique_together': {('recording', 'task_id')},
            },
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='type_recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RepackingApp.typerecordingmodel'),
        ),
        migrations.CreateModel(
            name='RecodingFileUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(path=pathlib.PurePosixPath('/home/grigoriy/PycharmProjects/RepackingPerfomanceVideos/RepackingProject'))),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('recording_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RepackingApp.recordingtaskidmodel', to_field='task_id')),
            ],
            options={
                'verbose_name': 'Файл конферении',
                'verbose_name_plural': 'Файлы конферений',
            },
        ),
        migrations.AddField(
            model_name='orderrecordingmodel',
            name='type_recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RepackingApp.typerecordingmodel'),
        ),
        migrations.AddField(
            model_name='orderrecordingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
