# Generated by Django 4.1.6 on 2026-04-06 05:54

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('RepackingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingmodel',
            name='analytic_file',
            field=models.FilePathField(blank=True, null=True, path=pathlib.PurePosixPath('/home/grigoriy/PycharmProjects/RepackingPerfomanceVideos/RepackingProject')),
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
