# Generated by Django 4.2.30 on 2026-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepackingApp', '0002_recordingmodel_analytic_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recodingfileusermodel',
            name='file',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='recordingmodel',
            name='analytic_file',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
