# Generated by Django 4.2.30 on 2026-06-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepackingApp', '0003_alter_recodingfileusermodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recodingfileusermodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='recordingmodel',
            name='analytic_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
