"""
Django settings for RepackingProject project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import sys
from pathlib import Path

import pytz
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (bool(int(os.getenv('DEBUG', 1))))

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(',')

INTERNAL_IPS = os.getenv("INTERNAL_IPS").split(',')

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split(',')
CORS_ORIGIN_WHITELIST = os.getenv("CORS_ORIGIN_WHITELIST").split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'AccountApp.apps.AccountAppConfig',
    'RepackingApp.apps.RepackingAppConfig',
    'core.apps.CoreAppConfig',
]

if DEBUG:
    # SILKY_PYTHON_PROFILER = True
    INSTALLED_APPS.append('debug_toolbar')
    # INSTALLED_APPS.append('silk')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # MIDDLEWARE.append("silk.middleware.SilkyMiddleware")
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = 'RepackingProject.urls'

LOGIN_URL = '/account/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'context_processors.context_processors.website_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'RepackingProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',

        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv("POSTGRES_DB", "postgres_db"),
        'USER': os.getenv("POSTGRES_USER", "postgres_user"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD", "postgres_pass"),
        'HOST': os.getenv("POSTGRES_HOST",),
        'PORT': int(os.getenv("POSTGRES_PORT")),
        'CONN_MAX_AGE': 60 * 10,
    }
}

AUTH_USER_MODEL = 'AccountApp.UserModel'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
USERNAME_FIELD = 'email'
ACCOUNT_EMAIL_REQUIRED = True


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# if DEBUG:
#     # Logging query language
    # LOGGING = {
    #     'version': 1,
    #     'disable_existing_loggers': False,
    #     'handlers': {
    #         'console': {
    #             'class': 'logging.StreamHandler',
    #         },
    #     },
    #     'loggers': {
    #         'django.db.backends': {
    #             'level': 'DEBUG',
    #             'handlers': ['console'],
    #         }
    #     },
    # }

# Session settings
if not "test" in sys.argv:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# Caches
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv('CACHE_REDIS', "redis://localhost:6379/0"),
    }
}
CACHE_TYPE_RECORDINGS = "type_recordings"
CACHE_PK_RECORDINGS = "{}-recordings"


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Novosibirsk'
TIME_ZONE_PYTZ = pytz.timezone(TIME_ZONE)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
static_join = os.path.join(BASE_DIR, 'static')
if DEBUG:
    STATICFILES_DIRS = [static_join]
else:
    STATIC_ROOT = static_join

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# BBB APIs settings
BBB_SHARED_SECRET = os.getenv("BBB_SHARED_SECRET")
BBB_RESOURCE = os.getenv("BBB_RESOURCE")
BBB_URL = os.getenv("BBB_URL")

# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")

BROKER_URL = os.getenv("CELERY_BROKER_URL")
BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600
}

# Redis settings
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT"))
REDIS_DB = int(os.getenv("REDIS_DB"))

# Email settings
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT"))
EMAIL_USE_TLS = (bool(int(os.getenv('EMAIL_USE_TLS', 1))))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("EMAIL_HOST_USER")

EMAIL_SENDER = (bool(int(os.getenv('EMAIL_SENDER', 1))))

# Site settings
SCHEMA = os.getenv("SCHEMA")
WEBSITE_NAME = os.getenv("WEBSITE_NAME")
DOMAIN = os.getenv("DOMAIN")
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL")

EXPIRATION_MINUTES = 20
SUCCESS_ATTEMPT_COUNT = 10
CONFIRMATION_CODE_SESSION = "confirm-code"

REDIS_KEY_CHECKER = "rediskeyckecker"
REDIS_KEY_ORDER_PROCESSED = "order-{}"
REDIS_KEY_ORDER_FAILED = "order-{}-failed"
REDIS_KEY_ORDER_CANCELLED = "order-{}-cancelled"

KIND_CODE_2FA = "2fa"
KIND_CODE_EMAIL = "email"
KIND_CODE_FORGOT_PASSWORD = "forgotpassword"
KIND_NOTIFY_PROCESSED_VIDEOS = "processedvideos"

# Nextcloud mydisk settings
NEXTCLOUD_RESOURCE = os.getenv("NEXTCLOUD_RESOURCE")
NEXTCLOUD_USER = os.getenv("NEXTCLOUD_USER")
NEXTCLOUD_PASSWORD = os.getenv("NEXTCLOUD_PASSWORD")
NEXTCLOUD_PATH = os.getenv("NEXTCLOUD_PATH")
NEXTCLOUD_SHARE_LINK = os.getenv("NEXTCLOUD_SHARE_LINK")
NEXTCLOUD_SHARE_LINK_PASSWORD = os.getenv("NEXTCLOUD_SHARE_LINK_PASSWORD")
